### ISSUE TITLE
[BUG] clustering algorithm is stuck with LDBC datagen-9_0-fb dataset

### ISSUE THREAD

**Issue by yecol** [alibaba/GraphScope#1850]
Bug report:
`clustering` algorithm is stuck with LDBC datagen-9_0-fb dataset, while the expected time would be hundred seconds.

**Comment by parkerzf** [comment]
The script we ran into the issue:


```
import graphscope as gs
gs.set_option(show_log=True)

sess = gs.session(addr="localhost:59001")

g = g.add_edges("/home/graphscope/data/fb85/datagen-8_5-fb.e.csv", 
                src_field="src", 
                dst_field="dst", 
                properties=["weight"],
                label="edge")

context = gs.wcc(g)
```

Note that the `datagen-8_5-fb.e.csv` is downloaded from [here](https://repository.surfsara.nl/datasets/cwi/graphalytics) and we uncompress the data and modified the `e` format file to a `csv` file as follows:
* add the header `src,dst,weight`
* replace the space to comma

**Comment by yecol** [comment]
Thanks, @parkerzf !

**Comment by yecol** [comment]
Hi @parkerzf 
This bug is fixed. 
Please verify by launching a session with the latest image:

```
...
sess = gs.session(addr="localhost:59001",      
    k8s_gs_image="registry.cn-hongkong.aliyuncs.com/graphscope/graphscope:latest")
...
```

**Comment by xarion** [comment]
@yecol we are still suffering from this problem. To configure that gs image, we added the following in our helm config file.
```
engines:
  image:
    name: registry.cn-hongkong.aliyuncs.com/graphscope/graphscope
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"
```
We have confirmed in our logs that the pod indeed uses the graphscope image with`latest` tag.

**Comment by acezen** [comment]
> graphscope
hi, @xarion ,  I try the `latest` tag graphscope image and the clustering computation could be done on datagen-9_0-fb, here is my session configuration:
```python
sess = gs.session(k8s_volumes=k8s_volumes, num_workers=4, k8s_gs_image="registry.cn-hongkong.aliyuncs.com/graphscope/graphscope:latest", k8s_vineyard_cpu=32, k8s_vineyard_mem="1Gi", k8s_coordinator_mem="8Gi", vineyard_shared_mem="200Gi", k8s_engine_cpu=64, k8s_engine_mem="200Gi")
```

btw, could you give me the `IMAGE ID` of `latest` tag  image,  It might be possible that the `latest` tag image has not updated when you retry the clustering algorithm.

**Comment by yecol** [comment]
@xarion , if you still get stuck, please let us know. Many thanks!

**Comment by xarion** [comment]
Hi, we are still stuck. For the 8.5 dataset, the clustering runs once without error (takes around 5 minutes), when we run it the second time the cluster crashes. For the 9.0 dataset, it has been running for the past 40 minutes. Here is a copy of the notebook that I've used https://gist.github.com/xarion/a78e9be69dd1fe8caaa4448559cd3130.

Here is our configuration.

The Docker image from `kubectl describe pods`
```
Image:         registry.cn-hongkong.aliyuncs.com/graphscope/graphscope:latest
Image ID:      docker-pullable://registry.cn-hongkong.aliyuncs.com/graphscope/graphscope@sha256:1c6da88d0f2f6e0acc2664f577567a0c9ec201a2428be31f74cd8ecf916c5b74
```

Our notebook snippets (using the 8.5 dataset).
```
!pip install graphscope-client==0.14.0
%==
import graphscope as gs
gs.set_option(show_log=True)
sess = gs.session(addr="localhost:59001")
g = sess.g()
%==
%%time
g = g.add_edges("/home/graphscope/data/fb85/datagen-8_5-fb.e.csv", 
                src_field="src", 
                dst_field="dst", 
                properties=["weight"],
                label="edge")
%==
%%time
context = gs.clustering(g)
%%time
context = gs.clustering(g)
```

Our helm configuration;
```
volumes:
  enabled: true
  items:
    data:
      type: hostPath
      field:
        type: Directory
        path: /efs
      mounts:
      - mountPath: /home/graphscope/data/
preemptive: true


engines:
  num_workers: 8
  log_level: INFO
  image:
    name: registry.cn-hongkong.aliyuncs.com/graphscope/graphscope
    tag: "latest"
  resources:
    requests:
      cpu: 25.0
      memory: 230Gi
    limits:
      cpu: 27.0
      memory: 245Gi


vineyard:
  daemonset: ""
  image:
    name: registry.cn-hongkong.aliyuncs.com/graphscope/graphscope
    tag: ""
  resources:
    requests:
      cpu: 0.5
      memory: 512Mi
    limits:
      cpu: 0.5
      memory: 512Mi
  shared_mem: 245Gi


etcd:
  image:
    name: quay.io/coreos/etcd
    tag: v3.4.13
  resources:
    requests:
      cpu: 0.5
      memory: 128Mi
    limits:
      cpu: 0.5
      memory: 128Mi


withJupyter: true
jupyter:
  image:
    name: registry.cn-hongkong.aliyuncs.com/graphscope/jupyter
    tag: ""
  resources:
    requests:
      cpu: 1.0
      memory: 4Gi
    limits:
      cpu: 1.0
      memory: 4Gi
  port: 30080
```

We are using 8 r6i.8xlarge instances (each having 32 CPUs and 256 GB of memory).
