### ISSUE TITLE
[BUG] Redundancy in Interactive graph schema: `relation` and `edge_strategy`

### ISSUE THREAD

**Issue by zhanglei1949** [alibaba/GraphScope#3411]
```YAML
relation: ONE_TO_MANY/ONE_TO_ONE/MANY_TO_MANY/MANY_TO_ONE
```

```YAML
x_csr_params:
  edge_strategy: Multiple/Single/None
```
These two fields define some overlapping things？
```YAML
ONE_TO_MANY:
  incoming_edge_strategy: Single
  outgoing_edge_strategy: Multiple
ONE_TO_ONE:
  incoming_edge_strategy: Single
  outgoing_edge_strategy: Single
MANY_TO_ONE:
  incoming_edge_strategy: Single
  outgoing_edge_strategy: Multiple
MANY_TO_MANY:
  incoming_edge_strategy: Multiple
  outgoing_edge_strategy: Multiple
```

EdgeStrategy: None
