### ISSUE TITLE
feat(interactive): Support setting the mutability of edge triplet

### ISSUE THREAD

**Issue by zhanglei1949** [alibaba/GraphScope#3449]
Need one more configuration in schema, to define whether the edge will be added/updated/deleted.
```yaml
      vertex_type_pair_relations:
        source_vertex: person
        destination_vertex: person
        relation: MANY_TO_MANY
        x_csr_params:
          edge_storage_strategy: BOTH_OUT_IN
          mutability: true
```

Default value should true.
