### ISSUE TITLE
Support docker-compose deployment for GraphScope

### ISSUE THREAD

**Issue by siyuan0322** [alibaba/GraphScope#3821]

**Comment by Thespica** [comment]
Hi @siyuan0322 

I wanna have a try! I have tried installing GraphScope with pip, with minikube, and with dev-container. Could you provide more descriptions about this issue? Are we going to provide docker-compose file for single machine deployment, or for k8s?

**Comment by siyuan0322** [comment]
@Thespica Hi, the docker compose deployment is supposed to have an alternative option for those users who doesn't have a k8s environment, it should support both single host deployment as well as multiple host deployment. 

Yes it's expected to provide a docker-compose file with all component. It should be similar with the helm k8s deployment.

**Comment by Thespica** [comment]
Hello @siyuan0322 

I met some errors when running docker images as [discussion here](https://github.com/alibaba/GraphScope/discussions/4119) descripted.

I have tried run containers of

- v6d
- gae
- gie-frontend
- gie executor
- gle
- coordinator
- jupiter

independently, but only v6d and jupiter ran successfully, while others exist without log or error message. Could you give me some suggestions?

Besides, here is my `docker-compose.yaml` for reference:

```yaml
version: '3.8'

services:
  coordinator:
    image: registry.cn-hongkong.aliyuncs.com/graphscope/coordinator:latest
    ports:
      - "30081:80"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.2'
          memory: 256M
    volumes:
      - /tmp/testingdata:/testingdata

  vineyard:
    image: vineyardcloudnative/vineyardd:latest
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 512M

  jupyter:
    image: registry.cn-hongkong.aliyuncs.com/graphscope/jupyter:latest
    ports:
      - "30080:8888"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  gae:
    image: registry.cn-hongkong.aliyuncs.com/graphscope/analytical:0.28.0
    deploy:
      resources:
        reservations:
          cpus: '1'
          memory: 1G

  gie_executor:
    image: registry.cn-hongkong.aliyuncs.com/graphscope/interactive-executor:0.28.0
    deploy:
      resources:
        reservations:
          cpus: '1'
          memory: 1G

  gie_frontend:
    image: registry.cn-hongkong.aliyuncs.com/graphscope/interactive-frontend:0.28.0
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 1G

  gle:
    image: registry.cn-hongkong.aliyuncs.com/graphscope/learning:0.28.0
    deploy:
      resources:
        reservations:
          cpus: '0.2'
          memory: 1G

volumes:
  testingdata:
    driver: local

```
