### ISSUE TITLE
[BUG] Import to interactive fails

### ISSUE THREAD

**Issue by zhanglei1949** [alibaba/GraphScope#3926]
graph.yaml
```
{
  "creation_time": "2024-06-14 15:05:22",
  "data_update_time": "2024-06-14 17:42:05",
  "description": "",
  "id": "7",
  "name": "test",
  "schema": {
    "edge_types": [
      {
        "primary_keys": [],
        "properties": [
          {
            "property_id": 0,
            "property_name": "weight",
            "property_type": {
              "primitive_type": "DT_DOUBLE"
            }
          }
        ],
        "type_id": 0,
        "type_name": "person_knows_person",
        "vertex_type_pair_relations": [
          {
            "destination_vertex": "person",
            "relation": "MANY_TO_MANY",
            "source_vertex": "person"
          }
        ]
      },
      {
        "primary_keys": [],
        "properties": [
          {
            "property_id": 0,
            "property_name": "weight",
            "property_type": {
              "primitive_type": "DT_DOUBLE"
            }
          }
        ],
        "type_id": 1,
        "type_name": "person_created_software",
        "vertex_type_pair_relations": [
          {
            "destination_vertex": "software",
            "relation": "MANY_TO_MANY",
            "source_vertex": "person"
          }
        ]
      }
    ],
    "vertex_types": [
      {
        "primary_keys": [
          "id"
        ],
        "properties": [
          {
            "property_id": 0,
            "property_name": "id",
            "property_type": {
              "primitive_type": "DT_SIGNED_INT32"
            }
          },
          {
            "property_id": 1,
            "property_name": "name",
            "property_type": {
              "primitive_type": "DT_SIGNED_INT32"
            }
          },
          {
            "property_id": 2,
            "property_name": "age",
            "property_type": {
              "primitive_type": "DT_DOUBLE"
            }
          }
        ],
        "type_id": 0,
        "type_name": "person",
        "x_csr_params": {
          "max_vertex_num": 8192
        }
      },
      {
        "primary_keys": [
          "id"
        ],
        "properties": [
          {
            "property_id": 0,
            "property_name": "id",
            "property_type": {
              "primitive_type": "DT_SIGNED_INT32"
            }
          },
          {
            "property_id": 1,
            "property_name": "name",
            "property_type": {
              "primitive_type": "DT_SIGNED_INT32"
            }
          },
          {
            "property_id": 2,
            "property_name": "lang",
            "property_type": {
              "primitive_type": "DT_SIGNED_INT32"
            }
          }
        ],
        "type_id": 1,
        "type_name": "software",
        "x_csr_params": {
          "max_vertex_num": 8192
        }
      }
    ]
  },
  "schema_update_time": "2024-06-14 15:05:22",
  "store_type": "mutable_csr",
  "stored_procedures": []
}
```

import.yaml
```yaml
{
  "edge_mappings": [
    {
      "column_mappings": [
        {
          "column": {
            "index": 2,
            "name": "weight"
          },
          "property": "weight"
        }
      ],
      "destination_vertex_mappings": [
        {
          "column": {
            "index": 1,
            "name": "software.id"
          },
          "property": "software"
        }
      ],
      "inputs": [
        "/home/graphscope/.graphscope/runtime/coordinator/dataset/person_created_software.csv"
      ],
      "source_vertex_mappings": [
        {
          "column": {
            "index": 0,
            "name": "person.id"
          },
          "property": "person"
        }
      ],
      "type_triplet": {
        "destination_vertex": "software",
        "edge": "person_created_software",
        "source_vertex": "person"
      }
    },
    {
      "column_mappings": [
        {
          "column": {
            "index": 2,
            "name": "weight"
          },
          "property": "weight"
        }
      ],
      "destination_vertex_mappings": [
        {
          "column": {
            "index": 1,
            "name": "person.id"
          },
          "property": "person"
        }
      ],
      "inputs": [
        "/home/graphscope/.graphscope/runtime/coordinator/dataset/person_knows_person.csv"
      ],
      "source_vertex_mappings": [
        {
          "column": {
            "index": 0,
            "name": "person.id"
          },
          "property": "person"
        }
      ],
      "type_triplet": {
        "destination_vertex": "person",
        "edge": "person_knows_person",
        "source_vertex": "person"
      }
    }
  ],
  "vertex_mappings": [
    {
      "column_mappings": [
        {
          "column": {
            "index": 0,
            "name": "id"
          },
          "property": "id"
        },
        {
          "column": {
            "index": 1,
            "name": "name"
          },
          "property": "name"
        },
        {
          "column": {
            "index": 2,
            "name": "age"
          },
          "property": "age"
        }
      ],
      "inputs": [
        "/home/graphscope/.graphscope/runtime/coordinator/dataset/person.csv"
      ],
      "type_name": "person"
    },
    {
      "column_mappings": [
        {
          "column": {
            "index": 0,
            "name": "id"
          },
          "property": "id"
        },
        {
          "column": {
            "index": 1,
            "name": "name"
          },
          "property": "name"
        },
        {
          "column": {
            "index": 2,
            "name": "lang"
          },
          "property": "lang"
        }
      ],
      "inputs": [
        "/home/graphscope/.graphscope/runtime/coordinator/dataset/software.csv"
      ],
      "type_name": "software"
    }
  ]
}
```

job
```
{
  "detail": {
    "graph_id": "12",
    "process_id": 58546
  },
  "end_time": "2024-06-17 10:40:50",
  "id": "25",
  "log": "WARNING: Logging before InitGoogleLogging() is written to STDERR\nI0617 02:40:50.411573 58546 loader_factory.cc:66] Registering loader: file, format:csv\nI0617 02:40:50.412225 58546 schema.cc:1131] Parse schema version: v0.0\nI0617 02:40:50.412293 58546 schema.cc:569] prop--1 name: id type: int32 strategy: \nI0617 02:40:50.412313 58546 schema.cc:569] prop-0 name: name type: int32 strategy: \nI0617 02:40:50.412321 58546 schema.cc:569] prop-1 name: age type: double strategy: \nI0617 02:40:50.412365 58546 schema.cc:569] prop--1 name: id type: int32 strategy: \nI0617 02:40:50.412374 58546 schema.cc:569] prop-0 name: name type: int32 strategy: \nI0617 02:40:50.412380 58546 schema.cc:569] prop-1 name: lang type: int32 strategy: \nI0617 02:40:50.412389 58546 schema.cc:992] Try to parse 2edge configuration\nI0617 02:40:50.412410 58546 schema.cc:955] edge person_created_software from person to software with 1 properties\nI0617 02:40:50.412436 58546 schema.cc:955] edge person_knows_person from person to person with 1 properties\nI0617 02:40:50.412441 58546 schema.cc:1146] Parse stored_procedures\nI0617 02:40:50.412962 58546 loading_config.cc:572] Got metadata key: delimiter value: |\nI0617 02:40:50.412971 58546 loading_config.cc:572] Got metadata key: header_row value: true\nW0617 02:40:50.412977 58546 loading_config.cc:624] No data location is configured, If it is intended, please ignore this warning. Proceeding assuming all files are give in absolute path\nI0617 02:40:50.412981 58546 loading_config.cc:629] scheme: file, data_location: , method: overwrite, delimiter: |, include header row: true\nI0617 02:40:50.412986 58546 loading_config.cc:637] vertex_mappings is set\nI0617 02:40:50.413002 58546 loading_config.cc:244] Successfully parsed vertex mapping size: 1\nI0617 02:40:50.413044 58546 loading_config.cc:244] Successfully parsed vertex mapping size: 2\nI0617 02:40:50.413064 58546 loading_config.cc:648] edge_mappings is set\nI0617 02:40:50.413069 58546 loading_config.cc:500]  Try to parse 2 edge configuration\nI0617 02:40:50.413079 58546 loading_config.cc:87] Column name for col_id: 0 is set to: person.id\nE0617 02:40:50.413084 58546 loading_config.cc:94] Expect mapped property name [id] for source vertex mapping, at index: 0, got: person\nW0617 02:40:50.413087 58546 loading_config.cc:397] Field [source_vertex_mappings] is not set for edge [person->[person_created_software]->software], using default choice: column_id 0\nI0617 02:40:50.413094 58546 loading_config.cc:87] Column name for col_id: 1 is set to: software.id\nE0617 02:40:50.413098 58546 loading_config.cc:94] Expect mapped property name [id] for source vertex mapping, at index: 0, got: software\nW0617 02:40:50.413102 58546 loading_config.cc:405] Field [destination_vertex_mappings] is not set for edge[person->[person_created_software]->software], using default choice: column_id 1\nI0617 02:40:50.413106 58546 loading_config.cc:411] src: person, dst: software src_column size:  2 dst_column 2\nI0617 02:40:50.413120 58546 loading_config.cc:432] Successfully parsed edge mapping size: 1\nI0617 02:40:50.413128 58546 loading_config.cc:458] src person dst software edge person_created_software path \"/home/graphscope/.graphscope/runtime/coordinator/dataset/person_created_software.csv\"\nI0617 02:40:50.413163 58546 loading_config.cc:87] Column name for col_id: 0 is set to: person.id\nE0617 02:40:50.413167 58546 loading_config.cc:94] Expect mapped property name [id] for source vertex mapping, at index: 0, got: person\nW0617 02:40:50.413172 58546 loading_config.cc:397] Field [source_vertex_mappings] is not set for edge [person->[person_knows_person]->person], using default choice: column_id 0\nI0617 02:40:50.413177 58546 loading_config.cc:87] Column name for col_id: 1 is set to: person.id\nE0617 02:40:50.413180 58546 loading_config.cc:94] Expect mapped property name [id] for source vertex mapping, at index: 0, got: person\nW0617 02:40:50.413184 58546 loading_config.cc:405] Field [destination_vertex_mappings] is not set for edge[person->[person_knows_person]->person], using default choice: column_id 1\nI0617 02:40:50.413187 58546 loading_config.cc:411] src: person, dst: person src_column size:  2 dst_column 2\nI0617 02:40:50.413201 58546 loading_config.cc:432] Successfully parsed edge mapping size: 2\nI0617 02:40:50.413209 58546 loading_config.cc:458] src person dst person edge person_knows_person path \"/home/graphscope/.graphscope/runtime/coordinator/dataset/person_knows_person.csv\"\nI0617 02:40:50.413236 58546 loading_config.cc:662] Finish parsing bulk load config file\nI0617 02:40:50.413615 58546 basic_fragment_loader.cc:132] Finish init vertex data\nI0617 02:40:50.413684 58546 basic_fragment_loader.cc:104] Finish init vertex status files\nI0617 02:40:50.413714 58546 csv_fragment_loader.cc:295] Loading vertices with single thread...\nI0617 02:40:50.413720 58546 abstract_arrow_fragment_loader.cc:188] Start init vertices for label software with 1 files.\nI0617 02:40:50.413730 58546 abstract_arrow_fragment_loader.h:377] Parsing vertex file:1 for label software\nI0617 02:40:50.413735 58546 abstract_arrow_fragment_loader.h:385] Parsing vertex file:/home/graphscope/.graphscope/runtime/coordinator/dataset/software.csv for label software\nI0617 02:40:50.413765 58546 csv_fragment_loader.cc:202] before Got all column names: 3id,name,lang\nI0617 02:40:50.413771 58546 csv_fragment_loader.cc:212] Got all column names: 3id,name,lang\nI0617 02:40:50.413775 58546 csv_fragment_loader.cc:227] Got all column names: 3id,name,lang\nI0617 02:40:50.413787 58546 csv_fragment_loader.cc:404] Include columns: 3\nI0617 02:40:50.413791 58546 csv_fragment_loader.cc:435] vertex_label: software property_name: name property_type: int32 ind: 1\nI0617 02:40:50.413805 58546 csv_fragment_loader.cc:435] vertex_label: software property_name: lang property_type: int32 ind: 2\nF0617 02:40:50.414512 58546 csv_fragment_loader.cc:37] Failed to create streaming reader for file: /home/graphscope/.graphscope/runtime/coordinator/dataset/software.csv error: In CSV column #1: CSV conversion error to int32: invalid value 'lop'\n*** Check failure stack trace: ***\n    @     0x7f3a49b61b03  google::LogMessage::Fail()\n    @     0x7f3a49b699d1  google::LogMessage::SendToLog()\n    @     0x7f3a49b617c2  google::LogMessage::Flush()\n    @     0x7f3a49b6378f  google::LogMessageFatal::~LogMessageFatal()\n    @     0x7f3a49ee95b8  gs::CSVStreamRecordBatchSupplier::CSVStreamRecordBatchSupplier()\n    @     0x7f3a49ef1120  _ZZN2gs17CSVFragmentLoader11addVerticesEhRKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EEENKUlhRKS7_RKNS_13LoadingConfigEE_clEhSD_SG_.isra.0\n    @     0x7f3a49ef1868  _ZNSt17_Function_handlerIFSt10shared_ptrIN2gs20IRecordBatchSupplierEEhRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS1_13LoadingConfigEEZNS1_17CSVFragmentLoader11addVerticesEhRKSt6vectorIS9_SaIS9_EEEUlhSB_SE_E_E9_M_invokeERKSt9_Any_dataOhSB_SE_\n    @     0x7f3a49e34dc7  gs::AbstractArrowFragmentLoader::addVertexRecordBatchImpl<>()\n    @     0x7f3a49dea788  gs::AbstractArrowFragmentLoader::AddVerticesRecordBatch()\n    @     0x7f3a49ee87b6  gs::CSVFragmentLoader::addVertices()\n    @     0x7f3a49eeb7e0  gs::CSVFragmentLoader::loadVertices()\n    @     0x7f3a49eeb8fd  gs::CSVFragmentLoader::LoadFragment()\n    @     0x558766365859  main\n    @     0x7f3a4956ed90  (unknown)\n    @     0x7f3a4956ee40  __libc_start_main\n    @     0x558766365f75  _start\n    @              (nil)  (unknown)\nI0617 02:40:50.428084 58546 bulk_loader.cc:32] Received signal 6, exiting...\nE0617 02:40:50.428092 58546 bulk_loader.cc:36] Received signal 6,Clearing directory: /tmp/interactive_workspace//data/12/temp_indices, exiting...\n",
  "start_time": "2024-06-17 10:40:50",
  "status": "SUCCESS",
  "type": "BULK_LOADING"
}
```
