### ISSUE TITLE
[BUG] Problem in StaticIrMetaFetcher

### ISSUE THREAD

**Issue by zhanglei1949** [alibaba/GraphScope#4309]
```
[2024-11-04 16:41:31,564][INFO][main][com.alibaba.graphscope.common.ir.meta.fetcher.StaticIrMetaFetcher:41] read meta: com.alibaba.graphscope.common.ir.meta.IrMeta@76b0ae1b
[2024-11-04 16:41:31,577][WARN][main][com.alibaba.graphscope.common.ir.meta.fetcher.StaticIrMetaFetcher:55] failed to read graph statistics, error is: java.lang.RuntimeException: java.lang.NullPointerException
```

**Comment by zhanglei1949** [comment]
modern_graph_statistics.json
```json
{
    "total_vertex_count": 6,
    "total_edge_count": 6,
    "vertex_type_statistics": [
        {
            "type_id": 0,
            "type_name": "person",
            "count": 4
        },
        {
            "type_id": 1,
            "type_name": "software",
            "count": 2
        }
    ],
    "edge_type_statistics": [
        {
            "type_id": 0,
            "type_name": "knows",
            "vertex_type_pair_statistics": [
                {
                    "source_vertex": "person",
                    "destination_vertex": "person",
                    "count": 2
                }
            ]
        },
        {
            "type_id": 1,
            "type_name": "created",
            "vertex_type_pair_statistics": [
                {
                    "source_vertex": "person",
                    "destination_vertex": "sofware",
                    "count": 4
                }
            ]
        }
    ]
}
```

**Comment by zhanglei1949** [comment]
interactive_config_test.yaml
```yaml
log_level: INFO
verbose_level: 10
default_graph: modern_graph
compute_engine:
  type: hiactor
  workers:
    - localhost:10000
  thread_num_per_worker: 1
  store:
    type: cpp-mcsr
  metadata_store:
    type: file # file/sqlite/etcd
compiler:
  planner:
    is_on: true
    opt: RBO
    rules:
      - FilterIntoJoinRule
      - FilterMatchRule
      - NotMatchToAntiJoinRule
  meta:
    reader:
      schema:
        uri: /workspaces/GraphScope/flex/interactive/examples/modern_graph/graph.yaml
        interval: 1000 # ms
      statistics:
        uri: /tmp/modern_graph_statistics.json
        interval: 86400000 # ms
  endpoint:
    default_listen_address: localhost
    bolt_connector:
      disabled: false
      port: 7687
    gremlin_connector:
      disabled: false
      port: 8182
  query_timeout: 40000
  gremlin_script_language_name: antlr_gremlin_calcite
http_service:
  default_listen_address: localhost
  admin_port: 7777
  query_port: 10000

```
