### ISSUE TITLE
[BUG] Can only get the properties for the first 8192 vertices

### ISSUE THREAD

**Issue by zhanglei1949** [alibaba/GraphScope#4383]
For example, for the following vertex type, the properties for the vertices with inner id > 8192 is all empty string.
```yaml
 - type_id: 5
      type_name: Paper
      properties:
        - property_id: 0
          property_name: id
          property_type:
            string:
              long_text: ""
        - property_id: 1
          property_name: published
          property_type:
            string:
              long_text: ""
        - property_id: 2
          property_name: year
          property_type:
            string:
              long_text: ""
        - property_id: 3
          property_name: month
          property_type:
            string:
              long_text: ""
        - property_id: 4
          property_name: title
          property_type:
            string:
              long_text: ""
        - property_id: 5
          property_name: authors
          property_type:
            string:
              long_text: ""
        - property_id: 6
          property_name: summary
          property_type:
            string:
              long_text: ""
        - property_id: 7
          property_name: journal_ref
          property_type:
            string:
              long_text: ""
        - property_id: 8
          property_name: doi
          property_type:
            string:
              long_text: ""
        - property_id: 9
          property_name: primary_category
          property_type:
            string:
              long_text: ""
        - property_id: 10
          property_name: categories
          property_type:
            string:
              long_text: ""
        - property_id: 11
          property_name: node_type
          property_type:
            string:
              long_text: ""
        - property_id: 12
          property_name: cited_by_count
          property_type:
            string:
              long_text: ""
        - property_id: 13
          property_name: Background_problem_definition
          property_type:
            string:
              long_text: ""
        - property_id: 14
          property_name: Background_problem_value
          property_type:
            string:
              long_text: ""
        - property_id: 15
          property_name: Background_existing_solutions
          property_type:
            string:
              long_text: ""
        - property_id: 16
          property_name: Topic
          property_type:
            string:
              long_text: ""
        - property_id: 17
          property_name: eprint
          property_type:
            string:
              long_text: ""
        - property_id: 18
          property_name: author
          property_type:
            string:
              long_text: ""
        - property_id: 19
          property_name: url
          property_type:
            string:
              long_text: ""
      primary_keys:
        - id
```
