### ISSUE TITLE
[BUG]  GraphScope can't run in the namespace with ResourceQuota limit.

### ISSUE THREAD

**Issue by lidongze0629** [alibaba/GraphScope#96]
**Describe the bug**

GraphScope can't create pods (such as GraphManager pod and gremlin server pod) in the namespace with ResourceQuota limit.

```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-demo
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 2Gi
```

```python
Error from server (Forbidden): : pods "xxxx" is forbidden: failed quota: mem-cpu-demo: must specify limits.cpu,limits.memory,requests.cpu,requests.memory
```
